[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.8"
stun-zc = { path = "../stun-zc" }
md5 = "0.7.0"
tokio = { version = "1.32.0", features = ["full"] }
rand = "0.8.5"
